import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        foreground: "var(--foreground)",
        "on-surface": "#221b0e",
        "outline-variant": "#d3c4ba",
        "on-secondary-container": "#650034",
        "primary-fixed-dim": "#e7bfa3",
        "on-error": "#ffffff",
        "inverse-surface": "#372f21",
        tertiary: "#40260b",
        "safety-orange": "#fb8500",
        "primary-container": "#573c27",
        "tertiary-container": "#593c1f",
        background: "#fff8f3",
        surface: "#fff8f3",
        "surface-container-low": "#fff2e0",
        "tertiary-fixed-dim": "#eabe97",
        "on-tertiary": "#ffffff",
        "amber-glow": "#ffb703",
        "creative-pink": "#ffadc6",
        "surface-dim": "#e6d8c4",
        primary: "#3e2613",
        "on-surface-variant": "#4f453e",
        "on-primary": "#ffffff",
        "surface-container": "#fbecd7",
        "secondary-fixed": "#ffd9e2",
        "surface-tint": "#765841",
        "inverse-on-surface": "#feefda",
        "on-secondary": "#ffffff",
        "surface-variant": "#efe1cc",
        "on-secondary-fixed-variant": "#8e004b",
        "secondary-container": "#fe5e9e",
        "electric-teal": "#219ebc",
        "on-primary-fixed-variant": "#5c412b",
        "surface-container-high": "#f5e6d1",
        "on-tertiary-container": "#d0a781",
        "on-error-container": "#93000a",
        "inverse-primary": "#e7bfa3",
        outline: "#81756d",
        "ocean-deep": "#023047",
        "on-tertiary-fixed": "#2d1600",
        "surface-bright": "#fff8f3",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "on-primary-container": "#cda78c",
        error: "#ba1a1a",
        "secondary-fixed-dim": "#ffb0c8",
        "sky-vibrant": "#8ecae6",
        "on-background": "#221b0e",
        secondary: "#b11f63",
        "on-tertiary-fixed-variant": "#5e4023",
        "primary-fixed": "#ffdcc4",
        "tertiary-fixed": "#ffdcbf",
        "on-primary-fixed": "#2b1605",
        "surface-container-highest": "#efe1cc",
        "on-secondary-fixed": "#3e001e",
        "wild-strawberry": "#e34989",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "20px",
        unit: "8px",
        "container-max": "1200px",
        gutter: "32px",
        "section-gap": "64px",
        "component-gap": "24px",
      },
      fontFamily: {
        "headline-lg-mobile": ["var(--font-space-grotesk)"],
        button: ["var(--font-space-grotesk)"],
        "body-lg": ["var(--font-poppins)"],
        "headline-md": ["var(--font-space-grotesk)"],
        "label-caps": ["ui-monospace", "monospace"],
        "body-md": ["var(--font-poppins)"],
        display: ["var(--font-space-grotesk)"],
        "headline-lg": ["var(--font-space-grotesk)"],
      },
      fontSize: {
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        button: ["16px", { lineHeight: "1", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-lg": ["20px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "1.5", letterSpacing: "0.1em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        display: ["80px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
        "headline-lg": ["48px", { lineHeight: "1.2", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
export default config;
